#!/bin/sh

VERSION=`python -c "from version import appversion; print '%4.2f' % appversion"`
VER=`python -c "from version import appversion; print int(round(appversion*100,0))"`
APPNAME=`python -c "from version import appname; print appname"`
APPLINUX=`python -c "from version import appname; print appname.lower().replace('-','')"`
RELEASE=1

rm -f ${APPNAME}_${VER}_src.zip
rm -f {APPLINUX}-$VERSION-$RELEASE.noarch.rpm
rm -f {APPLINUX}_$VERSION-$RELEASE_all.deb
rm -f ${APPNAME}_${VER}_mac.zip
rm -rf ${APPNAME}.app

PY='xpublish.py files.py utils.py version.py'

# linux
RPM=/tmp/${APPLINUX}
RPMRT=$RPM/root
rm -rf $RPM
mkdir -p $RPM/BUILD
mkdir -p $RPM/SOURCES
mkdir -p $RPM/SPECS
mkdir -p $RPM/RPMS/noarch
mkdir -p $RPMRT/usr/local/bin
mkdir -p $RPMRT/usr/local/lib/${APPLINUX}
cp linux/${APPLINUX}.desktop $RPMRT/usr/local/lib/${APPLINUX}/
cp -p linux/${APPLINUX}.spec $RPM/SPECS/
cp -p linux/${APPLINUX} $RPMRT/usr/local/bin/
for i in $PY; do cp -p "$i" $RPMRT/usr/local/lib/${APPLINUX}/; done
cp -p linux/${APPNAME}.png $RPMRT/usr/local/lib/${APPLINUX}/
rpmbuild -bb --buildroot $RPMRT --define "_topdir $RPM" --define "_unpackaged_files_terminate_build 0" --define "version $VERSION" --define "release $RELEASE" --quiet $RPM/SPECS/${APPLINUX}.spec
mv $RPM/RPMS/noarch/${APPLINUX}-$VERSION-$RELEASE.noarch.rpm .

# Debian/Ubuntu
mkdir -p $RPMRT/DEBIAN
mkdir -p $RPMRT/usr/local/share/applications
mkdir -p $RPMRT/usr/local/share/icons/hicolor/48x48/apps
cp -p linux/${APPLINUX}.desktop $RPMRT/usr/local/share/applications/
cp -p linux/${APPNAME}.png $RPMRT/usr/local/share/icons/hicolor/48x48/apps/${APPNAME}.png
echo Version: $VERSION-$RELEASE> $RPMRT/DEBIAN/control
cat   linux/control >> $RPMRT/DEBIAN/control
cp -p linux/postinst $RPMRT/DEBIAN/
sudo chown -R 0:0 $RPMRT/*
dpkg-deb -b $RPMRT .	# requires gnu-tar
sudo chown -R $USER:staff $RPMRT/*

# mac
mkdir -p ${APPNAME}.app/Contents/MacOS
cp -p MacOS/* ${APPNAME}.app/Contents/MacOS/
rm -f ${APPNAME}.app/Contents/MacOS/Info.plist
rm -f ${APPNAME}.app/Contents/MacOS/*.bak
for i in $PY; do cp -p "$i" ${APPNAME}.app/Contents/MacOS/; done
mkdir -p ${APPNAME}.app/Contents/Resources
sed s/appversion/$VERSION/ <MacOS/Info.plist >${APPNAME}.app/Contents/Info.plist
mv ${APPNAME}.app/Contents/MacOS/${APPNAME}.icns ${APPNAME}.app/Contents/Resources/
codesign -s "Developer ID Application: Jonathan Harris" ${APPNAME}.app
zip -r ${APPNAME}_${VER}_mac.zip ${APPNAME}.app
