#!/bin/sh

VERSION=`python -c "from version import appversion; print '%4.2f' % appversion"`
VER=`python -c "from version import appversion; print int(round(appversion*100,0))"`
APPNAME=`python -c "from version import appname; print appname"`
APPLINUX=`python -c "from version import appname; print appname.lower().replace('-','')"`
RELEASE=1

rm -f ${APPNAME}_${VER}_src.zip
rm -f {APPLINUX}-$VERSION-$RELEASE.noarch.rpm
rm -f {APPLINUX}_$VERSION-$RELEASE_all.deb
rm -f ${APPNAME}_${VER}_mac.zip
rm -rf ${APPNAME}.app

EXE=xpublish
PY='xpublish.py dopublish.py files.py utils.py version.py'

# linux
RPM=/tmp/${APPLINUX}
RPMRT=$RPM/root
rm -rf $RPM
mkdir -p $RPM/BUILD
mkdir -p $RPM/SOURCES
mkdir -p $RPM/SPECS
mkdir -p $RPM/RPMS/noarch
mkdir -p $RPMRT/usr/local/bin
mkdir -p $RPMRT/usr/local/lib/${APPLINUX}
mkdir -p $RPMRT/usr/local/share/applications
mkdir -p $RPMRT/usr/local/share/icons/hicolor/48x48/apps
mkdir -p $RPMRT/usr/local/share/icons/hicolor/128x128/apps
cp -p linux/${APPLINUX}.spec $RPM/SPECS/
cp -p linux/${APPLINUX} $RPMRT/usr/local/bin/
cp -p linux/${APPLINUX}.desktop $RPMRT/usr/local/share/applications/
cp -p linux/${APPNAME}.png $RPMRT/usr/local/share/icons/hicolor/48x48/apps/${APPLINUX}.png
cp -p linux/${APPNAME}-128.png $RPMRT/usr/local/share/icons/hicolor/128x128/apps/${APPLINUX}.png
for i in $PY; do cp -p "$i" $RPMRT/usr/local/lib/${APPLINUX}/; done
cp -p linux/${APPNAME}.png $RPMRT/usr/local/lib/${APPLINUX}/
rpmbuild -bb --buildroot $RPMRT --define "_target_os linux" --define "_target_vendor pc" --define "_topdir $RPM" --define "_unpackaged_files_terminate_build 0" --define "version $VERSION" --define "release $RELEASE" --quiet $RPM/SPECS/${APPLINUX}.spec
mv $RPM/RPMS/noarch/${APPLINUX}-$VERSION-$RELEASE.noarch.rpm .

# Debian/Ubuntu
mkdir -p $RPMRT/DEBIAN
echo Version: $VERSION-$RELEASE> $RPMRT/DEBIAN/control
cat   linux/control >> $RPMRT/DEBIAN/control
cp -p linux/postinst $RPMRT/DEBIAN/
mkdir -p $RPMRT/usr/local/share/doc/${APPLINUX}/
cp -p linux/copyright  $RPMRT/usr/local/share/doc/${APPLINUX}/
fakeroot "dpkg-deb -b $RPMRT ."	# requires gnu-tar

# mac
mkdir -p ${APPNAME}.app/Contents
sed s/appversion/${VERSION}/ <MacOS/Info.plist >${APPNAME}.app/Contents/Info.plist
mkdir -p ${APPNAME}.app/Contents/MacOS
cp -p MacOS/${EXE} ${APPNAME}.app/Contents/MacOS/
for i in $PY; do cp -p "$i" ${APPNAME}.app/Contents/MacOS/; done
mkdir -p ${APPNAME}.app/Contents/Resources
cp -p MacOS/*.icns ${APPNAME}.app/Contents/Resources/
# no external libs required for python2.5
python2.7 -OO ./bundledeps.py -o ${APPNAME}.app ${EXE}.py
xattr -r ${APPNAME}.app	# warn about superfluous resource forks / metadata
codesign --deep -s "Developer ID Application: Jonathan Harris" ${APPNAME}.app
ditto -ck --keepParent --sequesterRsrc ${APPNAME}.app ${APPNAME}_${VER}_mac.zip
