#!/bin/sh

export PYTHONPATH=$PYTHONPATH:..
VERSION=`python -c "from version import appversion; print '%4.2f' % appversion"`
VER=`python -c "from version import appversion; print int(round(appversion*100,0))"`
APPNAME=`python -c "from version import appname; print appname"`

APP=../${APPNAME}.app
EXE=xpublish
PY='xpublish.py dopublish.py files.py utils.py version.py'

rm -f ../${APPNAME}_${VER}_mac.zip
rm -rf ${APP}

mkdir -p ${APP}/Contents
sed s/appversion/${VERSION}/ <Info.plist >${APP}/Contents/Info.plist
mkdir -p ${APP}/Contents/MacOS
cp -p ${EXE} ${APP}/Contents/MacOS/
for i in $PY; do cp -p "../$i" ${APP}/Contents/MacOS/; done
mkdir -p ${APP}/Contents/Resources
cp -p *.icns ${APP}/Contents/Resources/
# no external libs required for python2.5
python2.7 -OO ./bundledeps.py -x setuptools -x pkg_resources -o ${APP} ../${EXE}.py
xattr -r ${APP}	# warn about superfluous resource forks / metadata
codesign --deep -s "Developer ID Application: Jonathan Harris" ${APP}
ditto -ck --keepParent --sequesterRsrc ${APP} ../${APPNAME}_${VER}_mac.zip
